Stat svc
CheTigor/event-feed pull request #1
Opened 2023-09-23 15:01 UTC by CheTigor

add statistic in project with base client. All package in docker

2023-09-24 07:01 UTC, YazykovMikhail requested changes

2023-09-24 07:01 UTC, YazykovMikhail commented on stats-server/stats-src/src/main/resources/schema.sql
> +
Зависит конечно от бизнеса, но можно сделать таблицу для app отдельную, 
```
CREATE TABLE IF NOT EXISTS apps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(150) NOT NULL,
  CONSTRAINT pk_aps PRIMARY KEY (id),
  CONSTRAINT UQ_APPS_NAME UNIQUE(name)
);
```

потому что они могут повторяться, а уже эндпоинты и ip будут разные. 
Можешь и так оставить но можешь и поправить

2023-09-24 07:01 UTC, YazykovMikhail commented on stats-server/stats-src/src/main/java/ru/practicum/service/StatisticServiceImpl.java
> +            if (unique && uri != null) {
uri != null врятли придет null из параметров, скорее всего придет пустой список. 
Так что стоит обрабатывать и null и то что он может быть пустой

2023-09-24 07:01 UTC, YazykovMikhail commented on stats-server/stats-src/src/main/java/ru/practicum/service/StatisticServiceImpl.java
> +            throw new RuntimeException(e.getMessage());
зачем тогда обрабатывать, если выьрасываешь тожесамое? 
Или не обрабатывай или выбрасывай свое.
Вообще RuntimeException обычно не обрабатывают, ведь нельзя предугадать что может быть в этом исключении, если оно выбросится, то выбросится

2023-09-24 07:01 UTC, YazykovMikhail commented on stats-server/common-DTO/pom.xml
> +    <artifactId>common-DTO</artifactId>
common-dto
называй пакеты маленькими буквами

2023-09-25 19:27 UTC, CheTigor commented on stats-server/stats-src/src/main/java/ru/practicum/service/StatisticServiceImpl.java
> +            throw new RuntimeException(e.getMessage());
Я ловлю DateTimeParse, а выкидываю DateTimeFormat - не смог в DateTimeParse настроить такой вывод, который бы меня устроил, поэтому создал свое исключение

2023-09-25 20:05 UTC, CheTigor commented on stats-server/stats-src/src/main/resources/schema.sql
> +
Я понял вашу мысль и согласен, что лучше эту информацию вынести в отдельную таблицу. Но я пока не готов рефакторить код под этот случай, там не так все просто. Поэтому оставлю без изменений

2023-09-27 13:54 UTC, merged